- results:
    folder: .
    lib_versions:
      pmdk:
        - pmembench_map
      safepm:
        - pmembench_map
      spp:
        - pmembench_map

- plot:
    plot_type: pmembench_map
    overhead_annot: false #not used
    benchmarks:
      - map_insert
      - map_get
      - map_remove
    y_axis: ops-per-second[1/sec]
    x_axis: type
    variants:
      - ops-per-thread
    plot_folder: plots/pmembench_map
