FROM ubuntu:20.04
ARG git_token
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get -qq install -y \
    pkg-config \
    libndctl-dev \
    libdaxctl-dev \
    pandoc \
    m4 \
    git \
    build-essential \
    python \
    cmake \
    binutils-dev \
    gdb \
    python3.9

# Install LLVM/CLANG
WORKDIR /
RUN git clone https://${git_token}@github.com/alexandrinapanfil/spp-pass.git /spp-pass
WORKDIR /spp-pass
RUN git checkout spplto_llvm
RUN git submodule update --init

WORKDIR /
COPY ./install_llvm.sh /install_llvm.sh
RUN chmod +x /install_llvm.sh
RUN /install_llvm.sh

#/llvm/ is the directory that llvm is installed
ENV PATH=$PATH:/llvm/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/llvm/lib
RUN ldconfig

ENV PMEM_MMAP_HINT=0
ENV PMEM_IS_PMEM_FORCE=1

WORKDIR /spp-pass
