FROM spp-llvm-clang-test:latest

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get -qq install -y \
    autoconf \
    automake \
    pkg-config \
    libndctl-dev \
    libdaxctl-dev \
    libglib2.0-dev \
    libncurses5-dev \
    libfuse-dev \
    libuv1-dev \
    pandoc \
    libfabric-dev \
    gdb \
    python3.9 \
    binutils-dev \
    m4 \
    bash \
    valgrind \
    # Dependencies to compile PMDK
    git \
    build-essential \
    # Install dependencies for memkind
    libnuma-dev \
    libtool \
    numactl \
    unzip \
    # Install dependencies for libpmemobj-cpp
    cmake \
    # Install dependencies for pmemkv
    libtbb-dev \
    # Install the dependencies for phoenix
    wget

# setup env variables --- to be moved to image create
ENV CC:=/llvm/bin/clang
ENV CXX:=/llvm/bin/clang++
ENV NM:=/llvm/bin/llvm-nm
ENV AR:=/llvm/bin/llvm-ar
ENV RANLIB:=/llvm/bin/llvm-ranlib

ENV CMAKE_C_COMPILER:=/llvm/bin/clang
ENV CMAKE_CXX_COMPILER:=/llvm/bin/clang++

# compile runtime lib
WORKDIR /spp-pass/runtime
RUN make

# build pmdk
WORKDIR /spp-pass/pmdk
COPY ./pmdk_spp.patch /spp-pass/pmdk/pmdk_spp.patch
RUN git apply pmdk_spp.patch
RUN make -j$(nproc)
RUN make install -j$(nproc)

# build libpmemobj-cpp
WORKDIR /
RUN git clone https://github.com/pmem/libpmemobj-cpp.git /libpmemobj-cpp
WORKDIR /libpmemobj-cpp
RUN git checkout stable-1.13
COPY ./libpmemobj-cpp_spp.patch /libpmemobj-cpp/libpmemobj-cpp_spp.patch
RUN git apply libpmemobj-cpp_spp.patch
RUN mkdir build
WORKDIR /libpmemobj-cpp/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOC=OFF -DBUILD_BENCHMARKS=OFF
RUN make -j$(nproc)
RUN make install -j$(nproc)

# build pmemkv
WORKDIR /
RUN git clone https://github.com/pmem/pmemkv.git /pmemkv
WORKDIR /pmemkv
RUN git checkout 1.4
COPY ./toolchain.cmake /pmemkv/toolchain.cmake
COPY ./pmemkv_spp.patch /pmemkv/pmemkv_spp.patch
RUN git apply pmemkv_spp.patch
RUN mkdir build
WORKDIR /pmemkv/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DENGINE_CMAP=ON -DENGINE_VCMAP=OFF -DENGINE_VSMAP=OFF -DENGINE_STREE=OFF -DBUILD_JSON_CONFIG=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOC=OFF -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake
RUN make -j$(nproc)
RUN make install -j$(nproc)

# build pmemkv-bench
WORKDIR /
RUN git clone https://github.com/pmem/pmemkv-bench.git /pmemkv-bench
WORKDIR /pmemkv-bench
RUN git checkout 32d94c0
COPY pmemkv-bench_spp.patch /pmemkv-bench/pmemkv-bench_spp.patch
RUN git apply pmemkv-bench_spp.patch
RUN make -j$(nproc)

# build phoenix benchmark - for SPP: the phoenix benchmark requires 31-TAG bits to work
WORKDIR /
RUN git clone https://github.com/dimstav23/phoenix.git /phoenix
WORKDIR /phoenix
RUN git checkout spp-run
COPY phoenix_spp.patch /phoenix/phoenix_spp.patch
RUN git apply phoenix_spp.patch
WORKDIR /phoenix/PM_phoenix-2.0/
RUN make
# get and unzip the appropriate input files for the phoenix benchmarks
WORKDIR /phoenix/PM_phoenix-2.0/tests/histogram
RUN wget http://csl.stanford.edu/\~christos/data/histogram.tar.gz
RUN tar -xvf histogram.tar.gz
WORKDIR /phoenix/PM_phoenix-2.0/tests/linear_regression
RUN wget http://csl.stanford.edu/\~christos/data/linear_regression.tar.gz
RUN tar -xvf linear_regression.tar.gz
WORKDIR /phoenix/PM_phoenix-2.0/tests/string_match
RUN wget http://csl.stanford.edu/\~christos/data/string_match.tar.gz
RUN tar -xvf string_match.tar.gz
WORKDIR /phoenix/PM_phoenix-2.0/tests/word_count
RUN wget http://csl.stanford.edu/\~christos/data/word_count.tar.gz
RUN tar -xvf word_count.tar.gz

WORKDIR /
